---
title: "R Notebook"
output: html_notebook
---

**Defining the Questions**

This document is meant as a reference point for questions to be answered during the project. For the fundamental questions highlighted in the project brief, these should remain consistent from the beginning of the project and should not be edited to a significant degree. However, as time and insights allow, supplementary questions to be answered can be added in addition to the core 6.

**The original questions with further comment and clarification**

We would like to to help us gain insights into how people feel about their local communities in Scotland. In particular, we are interested in the relationship between distance to outdoor space, and neighbourhood ratings.

*A lot of info should be able to be garnered fairly simply from the distance to green or blue space dataset included within the household survey and the brief ([link here](https://statistics.gov.scot/resource?uri=http%3A%2F%2Fstatistics.gov.scot%2Fdata%2Fgreen-or-blue-space-shs)). The variable that could be included in the "certain groups" category mentioned above are as follows:*

**Age**: 3 different distinct groups to explore here:

16-34 
35-64
65 years and older

**Distance to nearest Green or Blue space**: This will, I guess, be the main target variable for this particular question. There are 4 different groups and we will need to define what it means to have "local access" based on these:

A 5 minute walk or less 
An 11 minute walk or more 
Don't Know 
Within a 6-10 minute walk 

**Ethnicity**: Slightly disappointing that there is not a greater breakdown of groups in terms of this variable. As it is, the groups are as follows:

Other 
White

**Gender**: Split by Male and Female, although there is an all category which may allow an "Other" group to be created

**Household Type**: We have a breakdown of three distinct groups:

Adults
Pensioners 
With Children 

**Measure Type** This is an interesting one that needs to be explored further early on in the project. There are three options:

95% Lower Confidence Limit, Percent 
95% Upper Confidence Limit, Percent 
Percent 

**Reference Period** 2013 - 2019 available. Will be particularly important to check missing values. 

**SIMD Quintiles** A really intersesting variable if we are to touch on socio-economic links. Only two groups though:

20% most deprived 
80% least deprived 

**Type Of Tenure** This could be interesting as it suggests in itself a certain socio-economic dimension, although this may not necessarily be the case in isolation, but rather when combined with another element such as age. A larger list of groups include:

Owned Mortgage/Loan 
Owned Outright 
Private Rented 
Social Rented 

**Urban Rural Classification** A nice one to look at, although it may be fairly predictable:

Rural
Urban

**Reference Area** This says that it is provided by country and by council area by default, which adds an interesting geographical dimension to this. I'll need to see what the data looks like before this to check how robust such an analysis would be. 


**This is the first dataset to be looked at, with the further two datasets containing much the same breakdown, with one or two crucial caveats:**

**Neighbourhood rating dataset** - This dataset contains one additional variable and one adjusted one: 

*Neighbourhood rating* - Provide on a 4 point scale (Very Poor to Very Good), with a "No opinion" option also included.

*Walking Distance to nearest Greenspace* - So crucially, this is different from the above data set with only green space included (i.e. no blue space). Although the distance is still measured in terms of a time estimate, it is also different from the above with only more/less than 10 minutes walking distance or a Don't know as options. 


**Community belonging dataset** - Once again, same general variables, but with the same "Walking Distance" variable mentioned in the Neighbourhood rating dataset, and one unique variable:

*Community belonging* - This looks like it is accessed on a scale showing strength of sentiment. Once again four points (Not at all strongly to Very Strongly) with a "Don't know" option also included. 


**The main thing that I want to establish at this stage is whether or not these different datasets contain observations from the same source. In other words, is there anything to link individuals between the two datasets.**

In translating the following business questions into data questions, I think I need to define how each variable can be measured in a quantitative way to shed light on the original question. Thoughts and final definitions below. It was recommended that I try to answer each of these questions individually instead of answering them all in stages. With this in mind, I think I can safely get the data together for the first four questions and then answer each of these individually after this. 


1. Are there certain groups that have local access to green space?

*First of all, we need to define the elements in the second clause here.* 

Local access we can define as being within a ten minute walk of an individuals home. This should allow us to deal to use both variables mentioned above, although we might have to extend this definition to include up to 11 minutes given the second of the two variables. Strictly speaking, this would mean that a certain number of people who thought that they lived 11 minutes away from a green space may be misclassified, but given it is a subjective time estimate anyway I think that we can deal with this particular error. 

For the second definition here, we need to think of whether we use green space from the last two datasets or include the first dataset which seems to have "green and blue spaces". Checking in the notes for the datasets, the following is stated:

"The question asking about walking distance to nearest greenspace informs the National Indicator on Access to Green and Blue Spaces. However before 2019, even though the list of spaces included riversides and beaches, the question text used the term "green or open space". In 2019 for one half of the sample this was changed slightly to "green, blue or open spaces" to check if including the word "blue" made any difference to the response given to the question about walking distance or the biennial follow-up questions asking about satisfaction with and frequency of use of nearest green or blue space. No statistically significant difference was found."

This explanation is provided for two out of the three datasets, although somewhat confusingly these are not the same two datesets that make reference to only green space. With these caveats in mind, I am happy to go ahead and use both variables as common indicators for the same theme. 

So with all of this in mind, pending our checks on whether all the datasets relate to the same individuals, our first quantitative data definition will be:

*Are there certain groups, more than others, who report having access to green or blue spaces within 10 minutes of their homes.*


2. Are there groups that are lacking access?

In light of the above breakdown, I'd say that we should find the groups that are particularly likely to have green space more than 10 minutes walk away, once again with the same caveats and measures applied. So, just to be strict about this, the following definitin will apply:

*Are there certain groups, more than others, who report having access to green or blue spaces further than 10 minutes away from their homes.*


3. Are there big differences in how far people have to walk to access their green space?

To answer this one, my immediate thoughts are that we should take the population as a whole (i.e All in a lot of the variables) and then compare the difference between regions. If we have managed to gain insights into certain groups in the opening two questions, we could perhaps shed a bit more light on differences in the regions within the context of these differences. In a generally sense, this question could be considered a little bit tricky considering we only really have, at most, three categories representing a short, medium and long walk to green spaces, along with a don't know. We should perhaps consider renaming these categories as short, medium or long, although this would necessarily mean only using the first dataset which has thise level of granularity. Fundamentally, we'll want to show the following:

*Is the data on the overall sample very skewed towards one out of the three categories or is it relatively evenly dispersed amongst small, medium and long walks to green spaces.*

*Are similar skews replicated across different regions or are they consistent with the national average.*


4. Are there any differences between rural and urban areas?

This can probably be linked quite well into comparisons between other variables. In particular, since this is a binary classification, it would be great to take other variables and then just split these by rural and urban. Not quite sure how to word this at this stage but basically we should try and keep in the urban and rural classifier wherever we can during the analysis process. 











5. How do people in neighbourhoods with good access to green space differ from those who have no good access? Are there differences in how they rate their neighbourhoods? Are there differences in how they rate their communities?




6. Is there any way to predict which households would have higher ratings?
